
/* Drop Tables */

DROP TABLE ORDPRD CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;




/* Create Tables */

-- 회원
CREATE TABLE MEMBERS
(
	-- 유저ID
	MEM_ID varchar2(20) NOT NULL,
	-- 유저PW
	MEM_PW varchar2(12) NOT NULL,
	-- 유저이름
	MEM_NAME varchar2(10) NOT NULL,
	-- 유저주소
	MEM_ADDRESS varchar2(100) NOT NULL,
	PRIMARY KEY (MEM_ID)
);


-- 주문
CREATE TABLE ORDPRD
(
	-- 주문번호
	ORD_ID varchar2(5) NOT NULL,
	-- 유저ID
	MEM_ID varchar2(20) NOT NULL,
	-- 제품ID
	PRD_ID varchar2(20) NOT NULL,
	-- 수량
	ORD_NUM number NOT NULL,
	-- 금액
	ORD_PRICE number NOT NULL,
	PRIMARY KEY (ORD_ID)
);


-- 제품
CREATE TABLE PRODUCT
(
	-- 제품ID
	PRD_ID varchar2(20) NOT NULL,
	-- 제품이름
	PRD_TITLE varchar2(100) NOT NULL,
	-- 제품크기
	PRD_SIZE number NOT NULL,
	-- 제품색
	PRD_COLOR varchar2(20) NOT NULL,
	PRIMARY KEY (PRD_ID)
);



/* Create Foreign Keys */

ALTER TABLE ORDPRD
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBERS (MEM_ID)
;


ALTER TABLE ORDPRD
	ADD FOREIGN KEY (PRD_ID)
	REFERENCES PRODUCT (PRD_ID)
;



/* Comments */

COMMENT ON TABLE MEMBERS IS '회원';
COMMENT ON COLUMN MEMBERS.MEM_ID IS '유저ID';
COMMENT ON COLUMN MEMBERS.MEM_PW IS '유저PW';
COMMENT ON COLUMN MEMBERS.MEM_NAME IS '유저이름';
COMMENT ON COLUMN MEMBERS.MEM_ADDRESS IS '유저주소';
COMMENT ON TABLE ORDPRD IS '주문';
COMMENT ON COLUMN ORDPRD.ORD_ID IS '주문번호';
COMMENT ON COLUMN ORDPRD.MEM_ID IS '유저ID';
COMMENT ON COLUMN ORDPRD.PRD_ID IS '제품ID';
COMMENT ON COLUMN ORDPRD.ORD_NUM IS '수량';
COMMENT ON COLUMN ORDPRD.ORD_PRICE IS '금액';
COMMENT ON TABLE PRODUCT IS '제품';
COMMENT ON COLUMN PRODUCT.PRD_ID IS '제품ID';
COMMENT ON COLUMN PRODUCT.PRD_TITLE IS '제품이름';
COMMENT ON COLUMN PRODUCT.PRD_SIZE IS '제품크기';
COMMENT ON COLUMN PRODUCT.PRD_COLOR IS '제품색';



